#!/usr/bin/env python3
import os
import sys

def main():
    build_dir = sys.argv[1] if len(sys.argv) > 1 else "build_aarch64"
    output_file = os.path.join(build_dir, "embedded_bins.h")
    
    binaries = {
        "rc": "rc.elf",
        "echo": "echo.elf",
        "cat": "cat.elf",
        "ls": "ls.elf",
        "pwd": "pwd.elf",
        "mkdir": "mkdir.elf",
        "rm": "rm.elf"
    }
    
    print(f"Generating {output_file}...")
    
    with open(output_file, "w") as out:
        out.write("/* Automatically generated by embed_bins.py. Do not edit. */\n")
        out.write("#ifndef _EMBEDDED_BINS_H_\n")
        out.write("#define _EMBEDDED_BINS_H_\n\n")
        
        for name, filename in binaries.items():
            path = os.path.join(build_dir, filename)
            if not os.path.exists(path):
                print(f"Error: binary {path} does not exist!")
                sys.exit(1)
                
            size = os.path.getsize(path)
            print(f"Embedding {name} ({size} bytes) from {path}...")
            
            with open(path, "rb") as f:
                data = f.read()
                
            out.write(f"/* {filename} - {size} bytes */\n")
            out.write(f"unsigned char bin_{name}[] = {{\n")
            
            # Write bytes in chunks of 12 per line
            hex_data = []
            for i, b in enumerate(data):
                hex_data.append(f"0x{b:02x}")
                if (i + 1) % 12 == 0:
                    out.write("    " + ", ".join(hex_data) + ",\n")
                    hex_data = []
            if hex_data:
                out.write("    " + ", ".join(hex_data) + "\n")
            else:
                # Remove the trailing comma from the last line if no leftover
                pass
                
            out.write("};\n")
            out.write(f"unsigned int bin_{name}_len = {size};\n\n")
            
        out.write("#endif /* _EMBEDDED_BINS_H_ */\n")
        
    print("Embedding complete!")

if __name__ == "__main__":
    main()
